/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.User;
import Utility.DatabaseConnector;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import View.AgencyAdminFormPanel;
/**
 *
 * @author danie
 */
public class JFrame extends javax.swing.JFrame {
    private JTextField txtUsername;
    private JPasswordField txtPassword;
    private DatabaseConnector dbConnector;
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        dbConnector = new DatabaseConnector();
        txtUsername = jTextField1;
        txtPassword = jPasswordField1;
        
        InitDefaultBottomLayout();
    }
    
    public void InitDefaultBottomLayout() { 
//        HotelStuffFormPanel newFormJPanel = new HotelStuffFormPanel(this.bottomJPanel);
//        this.bottomJPanel.add(newFormJPanel);
//        CardLayout layout = (CardLayout) this.bottomJPanel.getLayout();
//        layout.next(this.bottomJPanel);
        bottomJPanel.setLayout(new CardLayout());
    
        HotelStuffFormPanel hotelStuffPanel = new HotelStuffFormPanel(this.bottomJPanel);
        bottomJPanel.add(hotelStuffPanel, "HotelStuff");

        AgencyAdminFormPanel agencyAdminPanel = new AgencyAdminFormPanel(this.bottomJPanel);
        bottomJPanel.add(agencyAdminPanel, "AgencyAdmin");

        AgencyStuffFormPanel agencyStuffPanel = new AgencyStuffFormPanel(this.bottomJPanel);
        bottomJPanel.add(agencyStuffPanel, "AgencyStuff");

        HotelAdminFormPanel hotelAdminPanel = new HotelAdminFormPanel(this.bottomJPanel);
        bottomJPanel.add(hotelAdminPanel, "HotelAdmin");

        CardLayout layout = (CardLayout) bottomJPanel.getLayout();
        layout.show(bottomJPanel, "HotelStuff");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        AgencyStuff = new javax.swing.JButton();
        AgencyAdmin = new javax.swing.JButton();
        HotelAdmin = new javax.swing.JButton();
        HotelStuff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        bottomJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1024, 582));

        AgencyStuff.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AgencyStuff.setText("AgencyStuff");
        AgencyStuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgencyStuffActionPerformed(evt);
            }
        });

        AgencyAdmin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AgencyAdmin.setText("AgencyAdmin");
        AgencyAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgencyAdminActionPerformed(evt);
            }
        });

        HotelAdmin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        HotelAdmin.setText("HotelAdmin");
        HotelAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelAdminActionPerformed(evt);
            }
        });

        HotelStuff.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        HotelStuff.setText("HotelStuff");
        HotelStuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelStuffActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AgencyAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgencyStuff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HotelAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HotelStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgencyAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgencyStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HotelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HotelStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(topJPanel);

        bottomJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(bottomJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgencyAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgencyAdminActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());
        // verify username&password
        User u = dbConnector.login(username, password);
        if (u != null) {
            CardLayout layout = (CardLayout) bottomJPanel.getLayout();
            layout.show(bottomJPanel, "AgencyAdmin");
        } else {
            JOptionPane.showMessageDialog(this, "user or password error！");
        }
    }//GEN-LAST:event_AgencyAdminActionPerformed

    private void AgencyStuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgencyStuffActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());
        // verify username&password
        User u = dbConnector.login(username, password);
        if (u != null) {
            CardLayout layout = (CardLayout) bottomJPanel.getLayout();
            layout.show(bottomJPanel, "AgencyStuff");
        } else {
            JOptionPane.showMessageDialog(this, "user or password error！");
        }
    }//GEN-LAST:event_AgencyStuffActionPerformed

    private void HotelAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotelAdminActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());
        // verify username&password
        User u = dbConnector.login(username, password);
        if (u != null) {
            CardLayout layout = (CardLayout) bottomJPanel.getLayout();
            layout.show(bottomJPanel, "HotelAdmin");
        } else {
            JOptionPane.showMessageDialog(this, "user or password error! ");
        }
    }//GEN-LAST:event_HotelAdminActionPerformed

    private void HotelStuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotelStuffActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());
        // verify username&password
        User u = dbConnector.login(username, password);
        if (u != null) {
            CardLayout layout = (CardLayout) bottomJPanel.getLayout();
            layout.show(bottomJPanel, "HotelStuff");
        } else {
            JOptionPane.showMessageDialog(this, "user or password error!");
        }
    }//GEN-LAST:event_HotelStuffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgencyAdmin;
    private javax.swing.JButton AgencyStuff;
    private javax.swing.JButton HotelAdmin;
    private javax.swing.JButton HotelStuff;
    private javax.swing.JPanel bottomJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel topJPanel;
    // End of variables declaration//GEN-END:variables
}
